### ISSUE TITLE
 DAOrayaki  Bounty | Task |  JPMorgan Chase, Toshiba and Ciena Build Quantum Key Distribution Network Used to Secure Blockchains

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#110]
Title: DAOrayaki  Bounty | Task |  JPMorgan Chase, Toshiba and Ciena Build Quantum Key Distribution Network Used to Secure Blockchains
类型: Translation
截止日期: 3/15/2022-3/17/2022
委员会审核: 3/18/2022-3/20/2022
要求:英译中； 3/15/2022-3/17/2022为创作者翻译时间，即创作者需要在3/17/2022号之前提交； 3/18/2022 -3/20/2022为委员会审核及投票时间。
链接:https://thequantuminsider.com/2022/02/19/jpmorgan-chase-toshiba-and-ciena-build-quantum-key-distribution-network-used-to-secure-blockchains/
Issue Link: https://github.com/DAOrayaki/DAOrayaki-Bounty/issues/108
Bounty Link: https://hackerlink.io/bounty/98
赏金: 30USDC

Title: DAOrayaki  Bounty | Task |  JPMorgan Chase, Toshiba and Ciena Build Quantum Key Distribution Network Used to Secure Blockchains
Type: Translation
Deadline: 3/15/2022-3/17/2022
Committee Decision: 3/18/2022-3/20/2022
Description: English to Chinese;3/15/2022-3/17/2022 is the creator's translation time, that is, creators need to submit before 3/17 ;3/18/2022-3/20/2022 is the committee review and voting time.
Link:https://thequantuminsider.com/2022/02/19/jpmorgan-chase-toshiba-and-ciena-build-quantum-key-distribution-network-used-to-secure-blockchains/
Issue Link: https://github.com/DAOrayaki/DAOrayaki-Bounty/issues/108
Bounty Link: https://hackerlink.io/bounty/98
Bounty: 30USDC

**Comment by fatfingererr** [comment]
fatfingererr will do the bounty

**Comment by fatfingererr** [comment]
I did the translation of issue #110, but I fall into the git problem on Windows because the file name with the character "|" is invalid in the filename, so I cannot check out the file "DAOrayaki Bounty | Task | 2022-03-16" so I also cannot make a PR.

![image](https://user-images.githubusercontent.com/23048798/158849985-96f07494-e7be-46eb-bd74-7b5162c6e271.png)

I am on a business trip today and tomorrow, so I only bring my laptop that os is Windows, I will be back home on Saturday then I will use the computer that is ubuntu for uploading. 

For the temporary workaround, please check the translation docs links that I should upload in the PR:
[https://docs.google.com/document/d/1p6T1FCu6Uouv5PFeK1zbNGtFyoRhoqOmBGoqltGogwI/edit?usp=sharing](https://docs.google.com/document/d/1p6T1FCu6Uouv5PFeK1zbNGtFyoRhoqOmBGoqltGogwI/edit?usp=sharing)

As a contributor here is my information: (fatfingererr#0697 fatfingererr@gmail.com)
