### ISSUE TITLE
2021 Review: Layer-1’s, Layer-2 Scaling Solutions, & The Future of ETH 2.0

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#21]
类型 : Translation
时间: 7天内
要求: 将链接中的英文文章翻译为中文。
链接: https://medium.com/coinmonks/2021-review-layer-1s-layer-2-scaling-solutions-the-future-of-eth-2-0-6d4bab27f769
Bounty : 70 U

Type: Translation
Deadline: Within 7 days
Requirement: Translate the English article in the link into Chinese.
Link: https://medium.com/coinmonks/2021-review-layer-1s-layer-2-scaling-solutions-the-future-of-eth-2-0-6d4bab27f769
Bounty: 70 U

**Comment by Will-Holden** [comment]
Hi depth-first, please make sure that u hackerlink account is bounded with your address. Otherwise it may cause a failed when claim your bounty

**Comment by depth-first** [comment]
Hi Will,
The hackerlink support haven't respond to my account issue.
I have contacted you with your mail. Please take a look.

**Comment by Will-Holden** [comment]
> Hi Will, The hackerlink support haven't respond to my account issue. I have contacted you with your mail. Please take a look.

What's issue, could u provide some info about that. I will try to contact hackerlink's support. 3q.

**Comment by depth-first** [comment]
The wallet is bind to my mail. I logged in to hackerlink with wallet. The account page shows my github account is linked.
I cannot click the ready button on the bounty page. I'm very confused.

I even created the hackerlink account with different mail/wallet again, but the issue is still the same.

I also found that I can link the github account with two Hackerlink accounts, which can be a bug.
Hackerlink might not link wallet-github correctly.

**Comment by depth-first** [comment]
I didn't bind phone to the hackerlink account. Is phone a must?

**Comment by depth-first** [comment]
I cannot click the participate button. It showed the ready button and I cannot undo it. I have tested many methods.
The problem is because the participate button is not undoable on the bounty page.
At the bounty page, it always linked the logged-in github account **automatically** without giving me the chance to link my wallet.

I have to unlinked the github account in hackerlink account page AND LOG-OUT my github account.
THEN the "participate" button reappeared on the bounty page.
I clicked "participate" and link both github and wallet.

Please test again.

**Comment by Will-Holden** [comment]
> 
3q, depth-first, I cant see if u wallet is bounded, u can check it in your personal page.

We will review u answer, 3q again for your contribution
